language: node_js

# test on two node.js versions: 0.10
node_js:
  - 0.10

services: 
  - redis-server
  - mongodb

addons:
  postgresql: "9.3"
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres